import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { VRButton } from 'three/addons/webxr/VRButton.js';
import { XRControllerModelFactory } from 'three/addons/webxr/XRControllerModelFactory.js';

const VERSION='0.4.0';
const recipes={
 'Velvet Sunset':{glass:'Highball',ice:3,method:'shaken',color:'#d9653c',ingredients:[['Vodka',45],['Orange',70],['Grenadine',15]],steps:['Highballglas wählen.','Vodka, Orange und Grenadine in den Shaker geben.','Drei Eiswürfel hinzufügen und kräftig shaken.','In das Glas gießen und servieren.']},
 'Blue Reverie':{glass:'Coupe',ice:2,method:'shaken',color:'#2584bd',ingredients:[['Gin',45],['Blue Curaçao',20],['Limette',25]],steps:['Coupe wählen.','Gin, Blue Curaçao und Limette in den Shaker geben.','Zwei Eiswürfel hinzufügen und shaken.','In die Coupe abseihen.']},
 'Rose After Dark':{glass:'Tumbler',ice:3,method:'shaken',color:'#a83f65',ingredients:[['Gin',40],['Beeren',35],['Limette',20]],steps:['Tumbler wählen.','Gin, Beeren und Limette in den Shaker geben.','Drei Eiswürfel hinzufügen und shaken.','In den Tumbler gießen.']}
};
const guests=[
{name:'Maya',order:'Velvet Sunset',dress:0x7d2f3d,skin:0xc48769,hair:0x20130f,lines:['„Ein Velvet Sunset, bitte. Und mach ihn nicht langweilig.“','„Du arbeitest sehr konzentriert. Ist das immer so?“','„Ich glaube, du hast verstanden, was ich mag.“'],choices:[['Nur bei Gästen, die Eindruck machen.','Präzision ist Teil eines guten Abends.'],['Heute habe ich einen besonders guten Grund.','Beim Mixen hilft mir Ruhe.'],['Dann hat sich das Zuhören gelohnt.','Das Rezept und dein Geschmack passen gut zusammen.']]},
{name:'Elena',order:'Blue Reverie',dress:0x244e69,skin:0xd2a181,hair:0x4c2c1d,lines:['„Eine Blue Reverie. Elegant, nicht zu süß.“','„Das Tablet ist praktisch. Aber kennst du die Rezepte auch auswendig?“','„Der Gießstil ist beinahe eine kleine Show.“'],choices:[['Für dich würde ich sogar ein neues erfinden.','Die Klassiker sitzen, das Tablet sichert Details.'],['Die wichtigen schon. Deinen merke ich mir.','Ich prüfe lieber einmal zu viel.'],['Die beste Show endet mit einem perfekten Drink.','Sauberes Arbeiten sieht meistens gut aus.']]},
{name:'Sofia',order:'Rose After Dark',dress:0x6e294d,skin:0xb9785d,hair:0x130e0d,lines:['„Rose After Dark. Frisch und nicht klebrig.“','„Wie viele Drinks brauchst du, um jemanden kennenzulernen?“','„Okay. Das war eine ziemlich gute Antwort.“'],choices:[['Einen, wenn das Gespräch stimmt.','Das hängt davon ab, wie ehrlich die Bestellung ist.'],['Bei dir reicht vielleicht dieser eine.','Ich lasse mir mit Urteilen Zeit.'],['Dann schulde ich dir jetzt noch einen guten Drink.','Danke. Jetzt muss nur noch die Balance stimmen.']]}
];
const liquids={Vodka:0xe4edf0,Orange:0xe88b32,Grenadine:0xa4162d,Gin:0xc8dde0,'Blue Curaçao':0x1680c1,Limette:0x72ad43,Beeren:0xa72d62};
const state={started:false,guest:0,dialogue:0,score:0,selectedRecipe:'Velvet Sunset',glass:null,shakerIngredients:[],shakerIce:0,shaken:false,glassIngredients:[],glassIce:0,pouring:false,busy:false};
const $=id=>document.getElementById(id);
let toastTimer;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800)}

const scene=new THREE.Scene();scene.background=new THREE.Color(0x08090d);scene.fog=new THREE.Fog(0x08090d,8,22);
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.04,60);camera.position.set(0,2.15,5.25);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');document.body.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.35,-.6);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=3;controls.maxDistance=7;controls.maxPolarAngle=1.55;
const M=(c,r=.5,m=.05)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
const glassMat=new THREE.MeshPhysicalMaterial({color:0xe9f3f3,roughness:.08,metalness:0,transmission:.93,thickness:.08,transparent:true,opacity:.38,side:THREE.DoubleSide});
function box(s,p,mat,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),mat);o.position.set(...p);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function cyl(rt,rb,h,p,mat,parent=scene,seg=32){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,seg),mat);o.position.set(...p);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function roundedBar(){box([8.7,.18,1.65],[0,1.05,-.18],M(0x54301e,.28));box([8.85,.08,1.74],[0,1.18,-.18],M(0xbc9056,.18,.62));box([8.45,1.0,.13],[0,.55,.59],M(0x171416,.5,.15));}
// room
box([16,.15,15],[0,-.08,0],M(0x151419,.78));box([16,6,.16],[0,3,-5.1],M(0x181318,.75));box([.16,6,12],[-7.8,3,.2],M(0x121218,.8));box([.16,6,12],[7.8,3,.2],M(0x121218,.8));
for(let i=-6;i<=6;i++)box([.07,4.7,.12],[i*1.05,3,-4.98],M(i%2?0x291a1c:0x201518,.7));
box([7.7,.14,.6],[0,1.42,-4.55],M(0x4d2a1a,.3));for(const y of [2.05,2.76,3.47])box([7.6,.08,.35],[0,y,-4.65],M(0xaf8148,.24,.6));
const bottleColors=[0x55251f,0x2b573b,0x8b692a,0x1e5065,0x7b3045,0x604f24];for(let row=0;row<3;row++)for(let i=0;i<14;i++){const x=-3.5+i*.54;const h=.34+((i*5+row)%4)*.045;cyl(.05,.072,h,[x,1.73+row*.71,-4.47],new THREE.MeshPhysicalMaterial({color:bottleColors[(i+row)%6],roughness:.2,transmission:.12,thickness:.08}));cyl(.025,.025,.09,[x,1.73+row*.71+h/2+.045,-4.47],M(0xb78a50,.25,.5))}
roundedBar();
scene.add(new THREE.HemisphereLight(0x83756f,0x21120f,1.2));const key=new THREE.SpotLight(0xffca92,55,14,Math.PI/5,.55,1.2);key.position.set(0,6,3);key.target.position.set(0,1,-1.8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key,key.target);const fill=new THREE.PointLight(0x8d5a7a,18,7);fill.position.set(-4,3,-1);scene.add(fill);const blue=new THREE.PointLight(0x376a89,16,7);blue.position.set(4,2.8,-2);scene.add(blue);
for(let i=-2;i<=2;i++){cyl(.012,.012,1.4,[i*1.55,4.6,-.3],M(0x252025,.3,.7));cyl(.27,.09,.3,[i*1.55,3.82,-.3],M(0x23181a,.3,.65));const l=new THREE.PointLight(0xffc782,4.2,3.5);l.position.set(i*1.55,3.62,-.3);scene.add(l)}

// guest
const guestRoot=new THREE.Group();guestRoot.position.set(0,0,-2.65);scene.add(guestRoot);
function buildGuest(g){guestRoot.clear();const skin=M(g.skin,.6),dress=M(g.dress,.32,.08),hair=M(g.hair,.72);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.35,.72,8,28),dress);torso.position.set(0,1.42,0);torso.castShadow=true;guestRoot.add(torso);cyl(.105,.12,.18,[0,1.94,0],skin,guestRoot);const head=new THREE.Mesh(new THREE.SphereGeometry(.265,40,32),skin);head.scale.set(.9,1.08,.94);head.position.set(0,2.17,0);head.castShadow=true;guestRoot.add(head);const cap=new THREE.Mesh(new THREE.SphereGeometry(.29,36,24,0,Math.PI*2,0,Math.PI*.68),hair);cap.position.set(0,2.24,-.02);guestRoot.add(cap);for(const s of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.019,14,10),M(0x171113,.3));eye.position.set(s*.082,2.18,.238);guestRoot.add(eye);const arm=cyl(.08,.07,.62,[s*.4,1.4,0],skin,guestRoot);arm.rotation.z=s*.24}const lip=new THREE.Mesh(new THREE.TorusGeometry(.05,.009,8,20,Math.PI),M(0x7f3448,.4));lip.position.set(0,2.065,.235);lip.rotation.z=Math.PI;guestRoot.add(lip)}

// workstation physical objects
const stationRoot=new THREE.Group();stationRoot.position.set(0,1.21,.1);scene.add(stationRoot);
const shaker=new THREE.Group();shaker.position.set(-.55,.02,0);stationRoot.add(shaker);const shakerBody=cyl(.18,.145,.55,[0,.28,0],M(0xb5b8ba,.16,.92),shaker);const shakerTop=cyl(.11,.18,.18,[0,.64,0],M(0xc6c9ca,.13,.95),shaker);const shakerCap=cyl(.075,.1,.09,[0,.77,0],M(0xd0d2d2,.12,.96),shaker);shakerTop.visible=shakerCap.visible=false;
const shakerLiquidGroup=new THREE.Group();shaker.add(shakerLiquidGroup);const shakerIceGroup=new THREE.Group();shaker.add(shakerIceGroup);
const pourStream=new THREE.Mesh(new THREE.CylinderGeometry(.018,.026,1,16),new THREE.MeshPhysicalMaterial({color:0xd9653c,transparent:true,opacity:.8,roughness:.1}));pourStream.visible=false;scene.add(pourStream);
const glassRoot=new THREE.Group();glassRoot.position.set(.55,.01,0);stationRoot.add(glassRoot);let currentGlassShell=null,currentGlassLiquid=null;const glassIceGroup=new THREE.Group();glassRoot.add(glassIceGroup);
const garnishTray=box([.7,.05,.35],[1.45,.03,0],M(0x5b3421,.4),stationRoot);
// ice well
box([.55,.22,.48],[-1.5,.11,0],M(0x6e7479,.2,.72),stationRoot);const wellIce=new THREE.Group();stationRoot.add(wellIce);for(let i=0;i<12;i++){const q=box([.09,.08,.09],[-1.7+(i%4)*.13,.22+Math.floor(i/4)*.05,(Math.random()-.5)*.22],new THREE.MeshPhysicalMaterial({color:0xcfe8ee,transmission:.65,transparent:true,opacity:.72,roughness:.12}),wellIce);q.rotation.set(Math.random(),Math.random(),Math.random())}
// bottles across front
const bottleRoot=new THREE.Group();bottleRoot.position.set(0,0,.62);stationRoot.add(bottleRoot);const names=Object.keys(liquids);names.forEach((n,i)=>{const x=-1.8+i*.6;const b=cyl(.085,.105,.48,[x,.28,0],new THREE.MeshPhysicalMaterial({color:liquids[n],roughness:.15,transmission:.25,transparent:true,opacity:.82}),bottleRoot);cyl(.036,.036,.14,[x,.59,0],M(0xc9ab70,.25,.55),bottleRoot);const label=box([.14,.13,.006],[x,.28,.105],M(0xe9dfca,.75),bottleRoot);label.userData.name=n});

function blendColors(items){if(!items.length)return new THREE.Color(0xd9653c);let r=0,g=0,b=0,w=0;for(const item of items){const c=new THREE.Color(liquids[item.name]);const amount=item.amount||30;r+=c.r*amount;g+=c.g*amount;b+=c.b*amount;w+=amount}return new THREE.Color(r/w,g/w,b/w)}
function volume(items){return items.reduce((s,x)=>s+x.amount,0)}
function rebuildShaker(){shakerLiquidGroup.clear();const vol=volume(state.shakerIngredients);if(vol>0){const h=Math.min(.43,.07+vol/260*.38);const liq=cyl(.135,.12,h,[0,.07+h/2,0],new THREE.MeshPhysicalMaterial({color:blendColors(state.shakerIngredients),roughness:.1,transparent:true,opacity:.78}),shakerLiquidGroup,40);liq.name='shakerLiquid'}shakerIceGroup.clear();for(let i=0;i<state.shakerIce;i++){const q=box([.085,.075,.085],[(Math.random()-.5)*.14,.18+i*.065,(Math.random()-.5)*.12],new THREE.MeshPhysicalMaterial({color:0xd6edf2,transmission:.65,transparent:true,opacity:.72,roughness:.1}),shakerIceGroup);q.rotation.set(Math.random(),Math.random(),Math.random())}shakerTop.visible=shakerCap.visible=state.shaken||state.busy}
function rebuildGlass(){glassIceGroup.clear();if(currentGlassShell)glassRoot.remove(currentGlassShell);if(currentGlassLiquid)glassRoot.remove(currentGlassLiquid);currentGlassShell=currentGlassLiquid=null;if(!state.glass)return;let h=.52,rTop=.18,rBot=.14,y=.27;if(state.glass==='Tumbler'){h=.34;rTop=.22;rBot=.2;y=.18}if(state.glass==='Coupe'){h=.19;rTop=.28;rBot=.07;y=.43;cyl(.025,.025,.3,[0,.18,0],glassMat,glassRoot);cyl(.14,.14,.025,[0,.02,0],glassMat,glassRoot)}currentGlassShell=new THREE.Mesh(new THREE.CylinderGeometry(rTop,rBot,h,48,1,true),glassMat);currentGlassShell.position.y=y;glassRoot.add(currentGlassShell);const vol=volume(state.glassIngredients);if(vol){const frac=Math.min(.92,vol/150);const lh=Math.max(.025,h*frac);currentGlassLiquid=new THREE.Mesh(new THREE.CylinderGeometry(rTop*.86,rBot*.88,lh,44),new THREE.MeshPhysicalMaterial({color:blendColors(state.glassIngredients),roughness:.1,transparent:true,opacity:.8}));currentGlassLiquid.position.y=y-h/2+lh/2+.015;glassRoot.add(currentGlassLiquid)}for(let i=0;i<state.glassIce;i++){const q=box([.075,.07,.075],[(Math.random()-.5)*.16,.1+i*.07,(Math.random()-.5)*.12],new THREE.MeshPhysicalMaterial({color:0xd5eef2,transmission:.7,transparent:true,opacity:.73,roughness:.1}),glassIceGroup);q.rotation.set(Math.random(),Math.random(),Math.random())}}

function buildTablet(){const tabs=$('recipeTabs');tabs.innerHTML='';Object.keys(recipes).forEach(name=>{const b=document.createElement('button');b.className='recipe-tab'+(name===state.selectedRecipe?' active':'');b.textContent=name;b.onclick=()=>{state.selectedRecipe=name;buildTablet();updateVRPanels()};tabs.appendChild(b)});const r=recipes[state.selectedRecipe];$('recipeCard').innerHTML=`<h3>${state.selectedRecipe}</h3><div class="recipe-meta">${r.glass} · ${r.ice} Eiswürfel · ${r.method==='shaken'?'Geschüttelt':'Gerührt'}</div><div class="ingredient-list">${r.ingredients.map(x=>`<span>${x[0]}</span><span>${x[1]} ml</span>`).join('')}</div><ol class="steps">${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol>`}
function renderDialogue(){const g=guests[state.guest];$('guestName').textContent=g.name;$('guestQuote').textContent=g.lines[state.dialogue];$('orderName').textContent=g.order;$('guestCounter').textContent=`${state.guest+1}/${guests.length}`;const root=$('choices');root.innerHTML='';g.choices[state.dialogue].forEach((txt,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=txt;b.onclick=()=>{state.score+=i===0?8:5;state.dialogue=Math.min(2,state.dialogue+1);renderDialogue();updateStats();updateVRPanels();toast(i===0?'Der Gast reagiert interessiert.':'Professionelle Antwort.')} ;root.appendChild(b)})}
function renderButtons(){const glasses=$('glassButtons');glasses.innerHTML='';['Highball','Coupe','Tumbler'].forEach(n=>{const b=document.createElement('button');b.className='ui-btn'+(state.glass===n?' active':'');b.textContent=n;b.onclick=()=>chooseGlass(n);glasses.appendChild(b)});const ing=$('ingredientButtons');ing.innerHTML='';names.forEach(n=>{const b=document.createElement('button');b.className='ui-btn';b.textContent=n;b.onclick=()=>addIngredient(n);ing.appendChild(b)})}
function updateStats(){$('score').textContent=String(state.score).padStart(4,'0');const inShaker=state.shakerIngredients.map(x=>x.name).join(', ');const inGlass=state.glassIngredients.map(x=>x.name).join(', ');$('vesselStatus').textContent=state.glassIngredients.length?`${state.glass}: ${Math.round(volume(state.glassIngredients))} ml`:state.shakerIngredients.length?`Shaker: ${Math.round(volume(state.shakerIngredients))} ml`:'Shaker leer';$('contentStatus').textContent=state.glassIngredients.length?`${inGlass} · ${state.glassIce} Eis`:state.shakerIngredients.length?`${inShaker} · ${state.shakerIce} Eis${state.shaken?' · geschüttelt':''}`:'Wähle Zutaten.';renderButtons()}
function chooseGlass(n){if(state.busy)return;state.glass=n;rebuildGlass();updateStats();updateVRPanels();toast(`${n} bereitgestellt`)}
function addIngredient(name){if(state.busy||state.glassIngredients.length)return toast('Leere zuerst das Glas.');const existing=state.shakerIngredients.find(x=>x.name===name);if(existing)existing.amount+=15;else state.shakerIngredients.push({name,amount:30});animateBottle(name);rebuildShaker();updateStats();updateVRPanels()}
function addIce(){if(state.busy)return;const target=state.glassIngredients.length?'glass':'shaker';if(target==='glass')state.glassIce=Math.min(5,state.glassIce+1);else state.shakerIce=Math.min(5,state.shakerIce+1);animateIce(target);rebuildShaker();rebuildGlass();updateStats();updateVRPanels()}
function animateBottle(name){state.busy=true;const i=names.indexOf(name),b=bottleRoot.children[i*3];if(!b){state.busy=false;return}const start=b.rotation.z,clock=new THREE.Clock();const timer=setInterval(()=>{const t=Math.min(1,clock.getElapsedTime()/0.55);b.rotation.z=-1.25*Math.sin(Math.PI*t);if(t>=1){b.rotation.z=start;clearInterval(timer);state.busy=false}},16);toast(`${name} in den Shaker gegossen`)}
function animateIce(target){const cube=box([.09,.08,.09],target==='glass'?[.55,.75,0]:[-.55,.8,0],new THREE.MeshPhysicalMaterial({color:0xd8f0f4,transmission:.7,transparent:true,opacity:.75,roughness:.1}),stationRoot);const endY=target==='glass'?.25:.28;let t=0;const timer=setInterval(()=>{t+=.06;cube.position.y=THREE.MathUtils.lerp(.8,endY,t);cube.rotation.x+=.14;cube.rotation.z+=.09;if(t>=1){stationRoot.remove(cube);clearInterval(timer)}},16);toast('Eis hinzugefügt')}
function shake(){if(state.busy)return;if(!state.shakerIngredients.length)return toast('Der Shaker ist leer.');if(!state.shakerIce)return toast('Füge Eis hinzu.');state.busy=true;shakerTop.visible=shakerCap.visible=true;const base=shaker.position.clone();let t=0;const timer=setInterval(()=>{t+=.11;shaker.rotation.z=Math.sin(t*5)*.42;shaker.position.y=base.y+Math.sin(t*10)*.08;if(t>Math.PI*2.2){clearInterval(timer);shaker.rotation.z=0;shaker.position.copy(base);state.shaken=true;state.busy=false;rebuildShaker();updateStats();updateVRPanels();toast('Kräftig geschüttelt')}} ,16)}
function pour(){if(state.busy)return;if(!state.glass)return toast('Wähle zuerst ein Glas.');if(!state.shakerIngredients.length)return toast('Der Shaker ist leer.');if(!state.shaken)return toast('Schließe und shake den Shaker zuerst.');state.busy=true;state.pouring=true;const startPos=shaker.position.clone();let t=0;pourStream.visible=true;pourStream.material.color.copy(blendColors(state.shakerIngredients));const timer=setInterval(()=>{t+=.025;const phase=Math.min(1,t/.35);shaker.position.x=THREE.MathUtils.lerp(startPos.x,.25,phase);shaker.position.y=THREE.MathUtils.lerp(startPos.y,.65,phase);shaker.rotation.z=THREE.MathUtils.lerp(0,-1.55,phase);const a=new THREE.Vector3();shaker.getWorldPosition(a);const b=new THREE.Vector3();glassRoot.getWorldPosition(b);b.y+=.42;const mid=a.clone().lerp(b,.5);pourStream.position.copy(mid);pourStream.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());pourStream.scale.y=a.distanceTo(b);if(t>.38&&t<1.12){const f=(t-.38)/.74;const amount=state.shakerIngredients.map(x=>({name:x.name,amount:x.amount*f}));state.glassIngredients=amount;state.glassIce=state.shakerIce;rebuildGlass()}if(t>=1.22){clearInterval(timer);pourStream.visible=false;state.glassIngredients=state.shakerIngredients.map(x=>({...x}));state.glassIce=state.shakerIce;state.shakerIngredients=[];state.shakerIce=0;state.shaken=false;shaker.position.copy(startPos);shaker.rotation.z=0;state.busy=false;state.pouring=false;rebuildShaker();rebuildGlass();updateStats();updateVRPanels();toast('Drink ins Glas gegossen')}} ,16)}
function resetDrink(){if(state.busy)return;state.shakerIngredients=[];state.shakerIce=0;state.shaken=false;state.glassIngredients=[];state.glassIce=0;rebuildShaker();rebuildGlass();updateStats();updateVRPanels();toast('Arbeitsstation geleert')}
function serve(){if(state.busy)return;if(!state.glassIngredients.length)return toast('Im Glas ist noch kein Drink.');const r=recipes[guests[state.guest].order];let glass=state.glass===r.glass?20:0;const actual=state.glassIngredients.map(x=>x.name),required=r.ingredients.map(x=>x[0]);let ingredients=required.filter(x=>actual.includes(x)).length*15-Math.max(0,actual.filter(x=>!required.includes(x)).length*8);let ice=Math.max(0,15-Math.abs(state.glassIce-r.ice)*5);let method=state.shaken?0:20; // shaker state reset after pour means successful pour implies shaken
 method=20;const dialogue=state.dialogue*6;const total=Math.max(0,glass+ingredients+ice+method+dialogue);state.score+=total;updateStats();$('resultScore').textContent=`+${total}`;$('resultTitle').textContent=total>=85?'Außergewöhnlich':total>=60?'Sehr gelungen':'Noch Luft nach oben';$('breakdown').innerHTML=[['Passendes Glas',glass],['Zutaten',ingredients],['Eis',ice],['Technik',method],['Gespräch',dialogue]].map(x=>`<span>${x[0]}</span><b>+${x[1]}</b>`).join('');$('result').classList.remove('hidden');showVRResult(total)}
function nextGuest(){$('result').classList.add('hidden');state.guest=(state.guest+1)%guests.length;state.dialogue=0;resetDrink();buildGuest(guests[state.guest]);renderDialogue();state.selectedRecipe=guests[state.guest].order;buildTablet();updateVRPanels()}

$('iceBtn').onclick=addIce;$('shakeBtn').onclick=shake;$('pourBtn').onclick=pour;$('resetBtn').onclick=resetDrink;$('serveBtn').onclick=serve;$('nextBtn').onclick=nextGuest;$('tabletToggle').onclick=()=>{$('tabletPanel').classList.toggle('hidden');$('tabletToggle').textContent=$('tabletPanel').classList.contains('hidden')?'Tablet öffnen':'Tablet schließen'};

// VR spatial UI
const vr={root:new THREE.Group(),buttons:[],screens:{}};scene.add(vr.root);vr.root.visible=false;const raycaster=new THREE.Raycaster(),tempMatrix=new THREE.Matrix4(),controllers=[];
function texPanel(w=1024,h=640){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return{canvas,ctx,texture}}
function drawPanel(t,title,kicker,lines){const {canvas:c,ctx:x,texture}=t;x.fillStyle='#111318';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#9b7544';x.lineWidth=5;x.strokeRect(8,8,c.width-16,c.height-16);x.fillStyle='#d3aa67';x.font='700 28px Arial';x.fillText(kicker.toUpperCase(),45,55);x.fillStyle='#f4f1ea';x.font='58px Georgia';x.fillText(title,45,130);x.fillStyle='#d0ccc4';x.font='30px Arial';let y=195;for(const line of lines){for(const row of wrap(x,line,c.width-90)){x.fillText(row,45,y);y+=40}y+=10}x.fillStyle='#777';x.font='22px Arial';x.fillText(`VELVET HOUR · v${VERSION}`,45,c.height-30);texture.needsUpdate=true}
function wrap(ctx,s,max){const out=[];let row='';for(const w of s.split(' ')){const n=row?row+' '+w:w;if(ctx.measureText(n).width>max&&row){out.push(row);row=w}else row=n}if(row)out.push(row);return out}
function makeScreen(parent,pos,size){const t=texPanel();const m=new THREE.Mesh(new THREE.PlaneGeometry(...size),new THREE.MeshBasicMaterial({map:t.texture}));m.position.set(...pos);parent.add(m);return{t,m}}
function makeVRButton(label,pos,size,action,parent){const g=new THREE.Group();g.position.set(...pos);parent.add(g);const mesh=box([size[0],size[1],.06],[0,0,0],M(0x392b22,.28,.3),g);const t=texPanel(700,220);drawPanel(t,label,'AUSWAHL',[]);const face=new THREE.Mesh(new THREE.PlaneGeometry(size[0]*.94,size[1]*.82),new THREE.MeshBasicMaterial({map:t.texture}));face.position.z=.032;g.add(face);mesh.userData.action=action;mesh.userData.group=g;vr.buttons.push(mesh);return mesh}
function panelBase(pos,rot,size){const g=new THREE.Group();g.position.set(...pos);g.rotation.set(...rot);box([size[0],size[1],.05],[0,0,0],M(0x121419,.3,.2),g);vr.root.add(g);return g}
const tablet3D=panelBase([-1.35,1.65,-.1],[0,.25,0],[1.2,1.3]);vr.screens.recipe=makeScreen(tablet3D,[0,.23,.032],[1.1,.75]);Object.keys(recipes).forEach((n,i)=>makeVRButton(n,[0,-.3-i*.22,.04],[1.05,.17],()=>{state.selectedRecipe=n;buildTablet();updateVRPanels()},tablet3D));
const guest3D=panelBase([1.35,1.65,-.1],[0,-.25,0],[1.2,1.3]);vr.screens.guest=makeScreen(guest3D,[0,.23,.032],[1.1,.75]);makeVRButton('Antwort A',[0,-.34,.04],[1.05,.18],()=>document.querySelectorAll('.choice')[0]?.click(),guest3D);makeVRButton('Antwort B',[0,-.57,.04],[1.05,.18],()=>document.querySelectorAll('.choice')[1]?.click(),guest3D);
const action3D=panelBase([0,1.1,.35],[-.15,0,0],[2.7,.78]);['Highball','Coupe','Tumbler'].forEach((n,i)=>makeVRButton(n,[-.92+i*.45,.22,.04],[.4,.18],()=>chooseGlass(n),action3D));names.forEach((n,i)=>makeVRButton(n,[-1.05+(i%4)*.7,-.02-Math.floor(i/4)*.22,.04],[.62,.17],()=>addIngredient(n),action3D));makeVRButton('Eis',[-.85,-.48,.04],[.38,.18],addIce,action3D);makeVRButton('Shaken',[-.35,-.48,.04],[.52,.18],shake,action3D);makeVRButton('Gießen',[.25,-.48,.04],[.52,.18],pour,action3D);makeVRButton('Servieren',[.92,-.48,.04],[.62,.18],serve,action3D);
vr.screens.result=makeScreen(guest3D,[0,.23,.05],[1.1,.75]);vr.screens.result.m.visible=false;
function updateVRPanels(){const r=recipes[state.selectedRecipe],g=guests[state.guest];drawPanel(vr.screens.recipe.t,state.selectedRecipe,'REZEPT',[`${r.glass} · ${r.ice} Eis · geschüttelt`,...r.ingredients.map(x=>`${x[0]} — ${x[1]} ml`)]);drawPanel(vr.screens.guest.t,g.name,`BESTELLT: ${g.order}`,[g.lines[state.dialogue],...g.choices[state.dialogue]]);vr.screens.guest.m.visible=true;vr.screens.result.m.visible=false}
function showVRResult(total){if(!renderer.xr.isPresenting)return;drawPanel(vr.screens.result.t,`+${total} Punkte`,'DRINK SERVIERT',[total>=85?'Außergewöhnlich gemixt.':'Die Bewertung ist abgeschlossen.','Nächster Gast über Desktop-Button oder Session verlassen.']);vr.screens.guest.m.visible=false;vr.screens.result.m.visible=true}
const cmf=new XRControllerModelFactory();for(let i=0;i<2;i++){const c=renderer.xr.getController(i);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-5)]),new THREE.LineBasicMaterial({color:0xd3aa67}));line.name='ray';c.add(line);c.addEventListener('selectstart',e=>{tempMatrix.identity().extractRotation(c.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(c.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(tempMatrix);const hit=raycaster.intersectObjects(vr.buttons,false)[0];if(hit){hit.object.userData.group.scale.set(.94,.94,.94);setTimeout(()=>hit.object.userData.group.scale.set(1,1,1),90);hit.object.userData.action();e.data?.gamepad?.hapticActuators?.[0]?.pulse?.(.45,45)}});scene.add(c);controllers.push(c);const grip=renderer.xr.getControllerGrip(i);grip.add(cmf.createControllerModel(grip));scene.add(grip)}
const vrButton=VRButton.createButton(renderer,{optionalFeatures:['local-floor','bounded-floor','hand-tracking']});vrButton.style.display='none';document.body.appendChild(vrButton);
renderer.xr.addEventListener('sessionstart',()=>{$('intro').classList.add('hidden');$('hud').classList.add('hidden');$('crosshair').classList.add('hidden');vr.root.visible=true;controls.enabled=false});renderer.xr.addEventListener('sessionend',()=>{vr.root.visible=false;if(state.started){$('hud').classList.remove('hidden');$('crosshair').classList.remove('hidden')}controls.enabled=true});

function startDesktop(){state.started=true;$('intro').classList.add('hidden');$('hud').classList.remove('hidden');$('crosshair').classList.remove('hidden')}
$('desktopStart').onclick=startDesktop;$('vrStart').onclick=()=>{vrButton.click()};
let vrSupported=false;if(navigator.xr?.isSessionSupported){navigator.xr.isSessionSupported('immersive-vr').then(v=>{vrSupported=v;$('vrStart').disabled=!v;$('vrStart').textContent=v?'Auf Meta Quest spielen':'WebXR hier nicht verfügbar'}).catch(()=>{$('vrStart').disabled=true})}else{$('vrStart').disabled=true;$('vrStart').textContent='WebXR hier nicht verfügbar'}

buildGuest(guests[0]);buildTablet();renderDialogue();renderButtons();rebuildShaker();rebuildGlass();updateStats();updateVRPanels();
setTimeout(()=>{$('loading').classList.add('hidden');$('intro').classList.remove('hidden')},350);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const t=clock.getElapsedTime();if(!renderer.xr.isPresenting)controls.update();guestRoot.position.y=Math.sin(t*1.05)*.012;guestRoot.rotation.y=Math.sin(t*.35)*.025;wellIce.children.forEach((x,i)=>x.rotation.y+=.001*(i+1));if(renderer.xr.isPresenting){for(const c of controllers){tempMatrix.identity().extractRotation(c.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(c.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(tempMatrix);const hit=raycaster.intersectObjects(vr.buttons,false)[0];for(const b of vr.buttons)b.material.emissive.set(b===hit?.object?0x4b3216:0x000000);const line=c.getObjectByName('ray');if(line)line.scale.z=hit?hit.distance/5:1}}renderer.render(scene,camera)});
